/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

/*****Includes*****/
#include "Stm32f103c6_GPIO_Driver.h"
#include "Stm32f103x6.h"

//Global variable
RCC_t*  RCC = RCC_Address;

/********************Function definition*************************/
//==========Clock_Init
 void Clock_Init()
{
	//Enable GPIOA Clock
	E_GPIOA_CLK();
	//Enable GPIOA Clock
	E_GPIOB_CLK();
}

//==========GPIO_Init
 void GPIO_Init()
{
	GPIO_Config_t PinConfig;

	/**********PinA1**********/
	//Choose Pin number
	PinConfig.GPIO_PinNumber = GPIO_PIN_1;
	//Choose Pin Mode
	PinConfig.GPIO_MODE = GPIO_MODE_INPUT_Floating;
    MCAL_GPIO_INIT(GPIOA, &PinConfig);

	/**********PinB1**********/
    //Choose Pin number
    PinConfig.GPIO_PinNumber = GPIO_PIN_1;
    //Choose Pin Mode
    PinConfig.GPIO_MODE = GPIO_MODE_OUTPUT_PP;
    //Choose Clock speed
    PinConfig.GPIO_Output_SPEED = GPIO_OUTPUT_SPEED_10M;
    MCAL_GPIO_INIT(GPIOB, &PinConfig);

	/**********PinA13**********/
	//Choose Pin number
	PinConfig.GPIO_PinNumber = GPIO_PIN_13;
	//Choose Pin Mode
	PinConfig.GPIO_MODE = GPIO_MODE_INPUT_Floating;
    MCAL_GPIO_INIT(GPIOA, &PinConfig);

	/**********PinB13**********/
    //Choose Pin number
    PinConfig.GPIO_PinNumber = GPIO_PIN_13;
    //Choose Pin Mode
    PinConfig.GPIO_MODE = GPIO_MODE_OUTPUT_PP;
    //Choose Clock speed
    PinConfig.GPIO_Output_SPEED = GPIO_OUTPUT_SPEED_10M;
    MCAL_GPIO_INIT(GPIOB, &PinConfig);

 }

//=======__delay__ Function
void __delay__(uint32_t Time )
{
	uint32_t i, j;
	for(i = 0;i < 255;i++)
	for(j = 0;j < 255;j++);
}


//===========main Function
int main(void)
{
	//Calling Init Function
	Clock_Init();
	GPIO_Init();

	//Infinite Loop
	while (1)
	{
		if (MCAL_GPIO_ReadPin(GPIOA, GPIO_PIN_1) == (uint8_t)0)
		{
			//Toggle Led
			MCAL_GPIO_TogglePin(GPIOB, GPIO_PIN_1);
			//========Single press
			while (MCAL_GPIO_ReadPin(GPIOA, GPIO_PIN_1) == 0);
		}
		else if (MCAL_GPIO_ReadPin(GPIOA, GPIO_PIN_13) == (uint8_t)1)
		{
			//Toggle Led
			MCAL_GPIO_TogglePin(GPIOB, GPIO_PIN_13);
		}
		__delay__(1);
	}
	return 0;
}

