/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#include <stdint.h>

//function prototype
void clock_init();
void EXTI0_IRQHandler();
void GPIO_Pin13_Output_Init();

//Macros for Addresses
#define GPIOA_BASE     0X40010800
#define RCC_BASE       0x40021000
#define EXTL_BASE      0x40010400
#define NVIC_BASE      0xE000E100
#define GPIOA_ODR      *((volatile uint32_t *)(GPIOA_BASE + 0x0c))
#define GPIOA_CRH      *((volatile uint32_t *)(GPIOA_BASE + 0x04))
#define RCC_APB2ENR    *((volatile uint32_t *)(RCC_BASE + 0x18))
#define EXTI_IMR       *((volatile uint32_t *)(EXTL_BASE + 0x0))
#define EXTI_RTSR      *((volatile uint32_t *)(EXTL_BASE + 0x08))
#define EXTI_PR        *((volatile uint32_t *)(EXTL_BASE + 0x14))
#define AFIO_EXTICR1   *((volatile uint32_t *)(GPIOA_BASE + 0x08))
#define GPIOA_CRL      *((volatile uint32_t *)(GPIOA_BASE + 0x0))
#define NVIC_EXTL0     *((volatile uint32_t *)(NVIC_BASE + 0x0))


//Main function
int main(void)
{
	//Init clock
	clock_init();
	//Init Pin13
	GPIO_Pin13_Output_Init();
	//Enable Floating Point
	GPIOA_CRL |= (1 << 2);
	//Make EXTL0_Mux Enable PortA0
	AFIO_EXTICR1 |= 0;
	//To Enable NonMask Register
	EXTI_IMR |= 1;
	//To Enable Rising Trigger
	EXTI_RTSR |= 1;
    //To Enable NVIC EXTLO Line
	NVIC_EXTL0 |= (1 << 6);

	//loop for infinity
	while(1);


    return 0;
}

//function to init clock
void clock_init()
{
	//Enable GPIO clock which is on APB2 bus
	RCC_APB2ENR  |= (1 << 2);
	//Enable ALT Clock which is on APB2 bus
	RCC_APB2ENR  |= 1;
}

//ISR for EXTI0
void EXTI0_IRQHandler()
{

	//toggle Led at Pin 13
	GPIOA_ODR ^= (1 << 13);
	//To Clear Pending Register
	EXTI_PR |= 1;
}
void GPIO_Pin13_Output_Init()
{
    //Init Register
	GPIOA_CRH    &= 0xff0fffff;
	//Make Pin13 output
	GPIOA_CRH    |= 0x00200000;



}



